### ISSUE TITLE
Webpack config for v3

### ISSUE THREAD

**Issue by Ehbraheem** [MoonTahoe/ski-day-counter-redux#2]
I tried following the lecture on my own and I had issues with my webpack config. I fixed it with *Eve Porcello's* video at this [link](https://www.lynda.com/React-js-tutorials/Migrating-webpack-3/496905/663728-4.html).

My solution is at this [link](https://github.com/Ehbraheem/ski-day-redux/blob/master/webpack.config.js)
But you have to install `babel-preset-env` instead of `babel-preset-latest` or use this as your `babel` rule instead 
`
{
				test: /\.js$/,
				exclude: /(node_modules)/,
				loader: 'babel-loader',
				query: {
					presets: ['latest', 'stage-0']
				}
			}`

**Comment by brucelane** [comment]
should I suggest you make a pull-request?

**Comment by Ehbraheem** [comment]
That will be fine but might add unnecessary ambiguity to the exercise files.

**Comment by brucelane** [comment]
by the way I'm trying with React 16 and the Router is broken too...

**Comment by Ehbraheem** [comment]
`React v16` is fine.

`React Router v4` comes with so many breaking changes. The API was almost rewritten. You can check the [doc for workaround](https://reacttraining.com/react-router/web/example/basic). But I'd advice you use v3.

For a quick fix:

- Delete your `node_modules` dir
- Replace `react-router` in your `package.json` with `"react-router": "^3.0.0"`
- Run `npm install` ( or `yarn` if you're using `Yarn` package manager) from your `CLI`

Everything should work out of the box after.

**Comment by MoonTahoe** [comment]
Yea, we haven't touched the source, it's still React 14 and Webpack v1. I believe. If you install from the repo the app works using these old versions.  

At some point we will upgrade the class to React 16, and then we will upgrade this repo too.

**Comment by MoonTahoe** [comment]
#3
